export const APPOINTMENT_FETCH = 'APPOINTMENT_FETCH';
export const APPOINTMENT_RESOLVE = 'APPOINTMENT_RESOLVE';
export const APPOINTMENTS_RESOLVE = 'APPOINTMENTS_RESOLVE';
export const APPOINTMENT_REJECT = 'APPOINTMENT_REJECT';
export const APPOINTMENT_CANCEL = 'APPOINTMENT_CANCEL';
