export const MYREQUEST_FETCH = "MYREQUEST_FETCH";
export const MYREQUEST_RESOLVE = "MYREQUEST_RESOLVE";
export const MYREQUESTS_RESOLVE = "MYREQUESTS_RESOLVE";
export const MYREQUEST_REJECT = "MYREQUEST_REJECT";
export const MYREQUEST_CANCEL = "MYREQUEST_CANCEL";
