export const REQUEST_FETCH = "REQUEST_FETCH";
export const REQUEST_RESOLVE = "REQUEST_RESOLVE";
export const REQUESTS_RESOLVE = "REQUESTS_RESOLVE";
export const REQUEST_REJECT = "REQUEST_REJECT";
export const REQUEST_CANCEL = "REQUEST_CANCEL";
